ASPNETIdentityManager-master/Controllers/RolesController.cs
using ASPNETIdentityManager.Contexts;
using ASPNETIdentityManager.Entities;
using ASPNETIdentityManager.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETIdentityManager.Controllers
{
    public class RolesController : Controller
    {
        private readonly ILogger<RolesController> logger;

        public RolesController(ILogger<RolesController> logger)
        {
            this.logger = logger;
        }

        public IActionResult Index([FromServices] UserDBContext dBContext, string roleName)
        {
            UsersAndRolesViewModel model = new UsersAndRolesViewModel();
            model.Roles = dBContext.Roles.Where(r =>
            string.IsNullOrEmpty(roleName) ? r.Name != null : r.Name.Contains(roleName)).Select(r => new Role()
            {
                IdentityRole = r,
                RoleClaims = dBContext.RoleClaims.Where(rc => rc.RoleId == r.Id).ToList()
            }).ToList();
            return View(model);
        }

        #region roles
        [HttpPost]
        public async Task<IActionResult> CreateRole([FromServices] UserDBContext dBContext, string roleName)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!string.IsNullOrEmpty(roleName))
                    {
                        dBContext.Roles.Add(new IdentityRole()
                        {
                            Name = roleName,
                            NormalizedName = roleName.ToUpperInvariant()
                        });
                        await dBContext.SaveChangesAsync();
                        return Json("OK");
                    }
                    else
                        return Json("Invalid request");
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message);
            }
            return Json("Invalid request");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteRole([FromServices] UserDBContext dBContext, [FromServices] UserManager<User> userManager, string roleID)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    IdentityRole role = dBContext.Roles.Where(r => r.Id == roleID).FirstOrDefault();
                    if (role != null)
                    {
                        List<IdentityRoleClaim<string>> claims = dBContext.RoleClaims.Where(uc => uc.RoleId == role.Id).ToList();
                        dBContext.RoleClaims.RemoveRange(claims);

                        List<IdentityUserRole<string>> userRoles = dBContext.UserRoles.Where(ur => ur.RoleId == role.Id).ToList();
                        dBContext.UserRoles.RemoveRange(userRoles);

                        List<User> users = (from ur in dBContext.UserRoles
                                            join u in dBContext.Users on ur.UserId equals u.Id
                                            where ur.RoleId == roleID
                                            select u).ToList();
                        foreach (User user in users)
                            await userManager.UpdateSecurityStampAsync(user);

                        dBContext.Roles.Remove(role);
                        await dBContext.SaveChangesAsync();
                        return Json("OK");
                    }
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message);
            }
            return Json("Invalid request");
        }
        [HttpPost]
        public async Task<IActionResult> AddClaimToRole([FromServices] UserDBContext dBContext, [FromServices] UserManager<User> userManager, string roleID, string claimType, string claimValue)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!string.IsNullOrEmpty(claimType) && !string.IsNullOrEmpty(claimValue))
                    {
                        dBContext.RoleClaims.Add(new IdentityRoleClaim<string>()
                        {
                            RoleId = roleID,
                            ClaimType = claimType,
                            ClaimValue = claimValue
                        });
                        await dBContext.SaveChangesAsync();

                        List<User> users = (from ur in dBContext.UserRoles
                                            join u in dBContext.Users on ur.UserId equals u.Id
                                            where ur.RoleId == roleID
                                            select u).ToList();
                        foreach (User user in users)
                            await userManager.UpdateSecurityStampAsync(user);
                        return Json("OK");
                    }
                    else
                        return Json("Values cant be null");
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message);
            }
            return Json("Invalid request");
        }
        [HttpPost]
        public async Task<IActionResult> RemoveClaimFromRole([FromServices] UserDBContext dBContext, [FromServices] UserManager<User> userManager, string roleID, string claimType, string claimValue)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<IdentityRoleClaim<string>> claims = dBContext.RoleClaims.Where(uc => uc.RoleId == roleID && uc.ClaimType == claimType && uc.ClaimValue == claimValue).ToList();
                    if (claims.Count > 0)
                    {
                        foreach (IdentityRoleClaim<string> claim in claims)
                            dBContext.RoleClaims.Remove(claim);
                        await dBContext.SaveChangesAsync();

                        List<User> users = (from ur in dBContext.UserRoles
                                            join u in dBContext.Users on ur.UserId equals u.Id
                                            where ur.RoleId == roleID
                                            select u).ToList();
                        foreach (User user in users)
                            await userManager.UpdateSecurityStampAsync(user);
                        return Json("OK");
                    }
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message);
            }
            return Json("Invalid request");
        }
        #endregion
    }
}

ASPNETIdentityManager-master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNETIdentityManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/modal.css" rel="stylesheet" />
</head>
<body>
    <!--<modal>-->
    <div class="container">
        <div class="row">
            <div id="modal" class="modal">
                <div class="modal-content col-6" style="left:25%">
                    <div class="modal-header">
                        <h2 id="modal-header"></h2>
                    </div>
                    <div class="modal-body" id="modal-body">
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--</modal>-->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Users<span class="sr-only">Users</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ASPNETIdentityManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/admin.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>